### PR TITLE
Solr is distributed as tar archive

### PR DESCRIPTION
**Pull request by pmoust**

### CODE REVIEW

**Comment by mkissam** [comment]
Hi Vamsee, do you plan to apply this patch in the near-future? Sits in the queue since dec 23, and your puppet module seems to be broken without this, because 4.7.2.tgz is a tar file not a tgz, and deployment fails with this error:
Error: /Stage[main]/Solr::Config/Exec[extract-solr]/returns: change from notrun to 0 failed: tar xzvf solr-4.7.2.tgz returned 2 instead of one of [0]

**Comment by pmoust** [comment]
@mkissam i did not have time to wait either so I forked it @ https://github.com/pmoust/puppet-solr
and published a module in forge https://forge.puppetlabs.com/pmoust/solr
```
puppet module install pmoust-solr
```

When @vamsee merges it I will mark mine as deprecated I suppose.

**Comment by mkissam** [comment]
@pmoust thanks, I'm looking for a module that is not abandoned, and supported some way. I'm considering to use this for a project at OpenStack, so I'm going to check how it fits to our use-case.

**Comment by pmoust** [comment]
@mkissam you can test out some docker containers with this module @ https://github.com/pmoust/docker-solr
They are on Docker hub so you can pull right away and examine.

**Comment by pmoust** [comment]
They are not optimal, but you get the idea.

**Comment by vamsee** [comment]
Apologies, every one. January has been a bit unusually travel-heavy from me. I'll do a new release this weekend with all the changes. Thanks for your contributions.

**Comment by pmoust** [comment]
@vamsee :+1:  :tropical_fish:

**Pull request merged**
